# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Underground
tagline:          'Underground'
description:      'Blog'
url:              http://ug.mahmutcavdar.com.tr

author:
  name:           'MC'
  url:            http://mahmutcavdar.com.tr/

paginate:         2
emailme:          mailto:mahmutcvdr@gmail.com

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/mcavdar

tags:


